"""Tests for ``skl.index`` and the ``skl index`` CLI verb."""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

import pytest
from click.testing import CliRunner

from skl import __version__
from skl.cli import main
from skl.index import regenerate_index


def _make_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    (repo / "skill-repo.yaml").write_text(
        f"""\
schema_version: 1
name: host
visibility: internal
skl_version: ">={__version__},<99.0"
shared_kit:
  source: github.com/example/kit
  version: "1.0.0"
enabled_platforms: []
"""
    )
    return repo


def _make_skill(repo: Path, name: str, *, content: str | None = None) -> Path:
    skill_root = repo / "skills" / name
    skill_root.mkdir(parents=True)
    if content is None:
        content = dedent(
            f"""\
            ---
            name: {name}
            description: A skill named {name}.
            skl:
              schema_version: 1
              display_name: {name.title()}
              status: active
              lifecycle: business_development
              enabled_platforms: [claude-code, m365]
            ---

            # {name.title()}

            ## Capabilities
            - Things.

            ## Workflow
            1. Do.

            ## Edge Cases
            - None.

            ## Examples
            Use.
            """
        )
    (skill_root / "SKILL.md").write_text(content)
    return skill_root


# ---------------------------------------------------------------------------
# regenerate_index
# ---------------------------------------------------------------------------


def test_regenerate_index_writes_file(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _make_skill(repo, "alpha")
    path = regenerate_index(repo)
    assert path == repo / "skills" / "SKILLS_INDEX.md"
    assert path.is_file()


def test_index_contains_header_and_table(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _make_skill(repo, "alpha")
    path = regenerate_index(repo)
    text = path.read_text()
    assert text.startswith("# Skills index")
    assert "Auto-generated by `skl index`" in text
    assert "| Name | Display | Status | Lifecycle | Platforms | Description |" in text


def test_index_lists_each_skill(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _make_skill(repo, "alpha")
    _make_skill(repo, "beta")
    text = regenerate_index(repo).read_text()
    assert "`alpha`" in text
    assert "`beta`" in text


def test_index_is_sorted_by_skill_name(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _make_skill(repo, "charlie")
    _make_skill(repo, "alpha")
    _make_skill(repo, "bravo")
    text = regenerate_index(repo).read_text()
    alpha = text.index("`alpha`")
    bravo = text.index("`bravo`")
    charlie = text.index("`charlie`")
    assert alpha < bravo < charlie


def test_index_is_deterministic(tmp_path: Path) -> None:
    """Same input set -> byte-identical output. Tests can rely on this for CI drift."""
    repo = _make_repo(tmp_path)
    _make_skill(repo, "alpha")
    _make_skill(repo, "beta")
    first = regenerate_index(repo).read_text()
    second = regenerate_index(repo).read_text()
    assert first == second


def test_index_with_no_skills_returns_empty_table(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    (repo / "skills").mkdir()
    text = regenerate_index(repo).read_text()
    assert "# Skills index" in text
    assert "No skills found" in text


def test_index_raises_when_skills_dir_missing(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    with pytest.raises(FileNotFoundError):
        regenerate_index(repo)


def test_index_skips_unparseable_skill(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _make_skill(repo, "good")
    # Broken SKILL.md (no frontmatter)
    bad_root = repo / "skills" / "broken"
    bad_root.mkdir(parents=True)
    (bad_root / "SKILL.md").write_text("Just body, no frontmatter.\n")
    text = regenerate_index(repo).read_text()
    assert "`good`" in text
    assert "broken" not in text


def test_index_escapes_pipes_in_description(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _make_skill(
        repo,
        "pipey",
        content=dedent(
            """\
            ---
            name: pipey
            description: A skill with a | pipe in its description.
            skl:
              schema_version: 1
              display_name: Pipey
              status: active
              enabled_platforms: []
            ---

            # Pipey
            ## Capabilities
            - x
            ## Workflow
            1. x
            ## Edge Cases
            - x
            ## Examples
            x
            """
        ),
    )
    text = regenerate_index(repo).read_text()
    assert r"a \| pipe" in text


def test_index_truncates_long_descriptions(tmp_path: Path) -> None:
    long_desc = "x " * 100  # 200 chars, well over the 120-char cell limit
    repo = _make_repo(tmp_path)
    _make_skill(
        repo,
        "longy",
        content=dedent(
            f"""\
            ---
            name: longy
            description: {long_desc}
            skl:
              schema_version: 1
              display_name: Longy
              status: active
              enabled_platforms: []
            ---

            # Longy
            ## Capabilities
            - x
            ## Workflow
            1. x
            ## Edge Cases
            - x
            ## Examples
            x
            """
        ),
    )
    text = regenerate_index(repo).read_text()
    # The first table data line contains the truncated description.
    data_line = next(line for line in text.splitlines() if line.startswith("| `longy`"))
    assert "..." in data_line
    assert len(data_line) < 250  # sanity: not the full 200-char string


def test_index_only_takes_first_line_of_multiline_description(tmp_path: Path) -> None:
    repo = _make_repo(tmp_path)
    _make_skill(
        repo,
        "multi",
        content=dedent(
            """\
            ---
            name: multi
            description: |
              First line of the description.
              Second line that should not appear in the table.
            skl:
              schema_version: 1
              display_name: Multi
              status: active
              enabled_platforms: []
            ---

            # Multi
            ## Capabilities
            - x
            ## Workflow
            1. x
            ## Edge Cases
            - x
            ## Examples
            x
            """
        ),
    )
    text = regenerate_index(repo).read_text()
    data_line = next(line for line in text.splitlines() if line.startswith("| `multi`"))
    assert "First line of the description" in data_line
    assert "Second line" not in data_line


# ---------------------------------------------------------------------------
# CLI integration
# ---------------------------------------------------------------------------


@pytest.fixture
def runner() -> CliRunner:
    return CliRunner()


def test_cli_index_outside_repo_errors(runner: CliRunner, tmp_path: Path) -> None:
    with runner.isolated_filesystem(temp_dir=tmp_path):
        result = runner.invoke(main, ["index"])
        assert result.exit_code != 0
        assert "not inside a skill-host repo" in result.output


def test_cli_index_writes_file(
    runner: CliRunner, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _make_repo(tmp_path)
    _make_skill(repo, "alpha")
    monkeypatch.chdir(repo)
    result = runner.invoke(main, ["index"])
    assert result.exit_code == 0, result.output
    assert "wrote skills/SKILLS_INDEX.md" in result.output
    assert (repo / "skills" / "SKILLS_INDEX.md").is_file()


def test_cli_index_no_skills_dir_errors(
    runner: CliRunner, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _make_repo(tmp_path)
    monkeypatch.chdir(repo)
    result = runner.invoke(main, ["index"])
    assert result.exit_code != 0
    assert "no skills/ directory" in result.output
