"""Regenerate ``skills/SKILLS_INDEX.md`` from the current set of SKILL.md files.

Output is a markdown table with one row per skill, sorted by skill name.
The file is intended to be checked in - it gives non-developer colleagues
a one-page directory of what's in a skill-host repo.

Determinism: same input set produces byte-identical output. Authors can
re-run ``skl index`` from CI; if the file diverges, CI fails.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from skl.skill_md import SkillParseError, parse_skill_md

_INDEX_FILENAME = "SKILLS_INDEX.md"

_DESCRIPTION_MAX_CHARS = 120


@dataclass(frozen=True)
class IndexRow:
    """One skill's row in the index. Names mirror the column headers."""

    name: str
    display_name: str
    status: str
    lifecycle: str
    platforms: str
    description: str


def regenerate_index(repo_root: Path) -> Path:
    """Write ``<repo_root>/skills/SKILLS_INDEX.md`` from the current skill set.

    Returns the absolute path written. Raises :class:`FileNotFoundError` if
    no ``skills/`` directory exists. Skills whose SKILL.md fails to parse
    are skipped (caller should run ``skl validate`` to surface the error).
    """
    skills_dir = repo_root / "skills"
    if not skills_dir.is_dir():
        raise FileNotFoundError(f"no skills/ directory at {skills_dir}")

    rows: list[IndexRow] = []
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        try:
            skill = parse_skill_md(skill_md)
        except SkillParseError:
            continue
        rows.append(
            IndexRow(
                name=skill.name or skill_md.parent.name,
                display_name=skill.display_name or "",
                status=skill.status or "",
                lifecycle=str(skill.skl.get("lifecycle") or ""),
                platforms=", ".join(skill.enabled_platforms),
                description=_summarise(skill.description or ""),
            )
        )

    index_path = skills_dir / _INDEX_FILENAME
    index_path.write_text(_render_index(rows))
    return index_path


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _render_index(rows: list[IndexRow]) -> str:
    header = [
        "# Skills index",
        "",
        "Auto-generated by `skl index`. Do not edit by hand; re-run the command after",
        "adding / renaming / deprecating skills.",
        "",
    ]
    if not rows:
        return "\n".join([*header, "No skills found under `skills/`.", ""])

    header.extend(
        [
            "| Name | Display | Status | Lifecycle | Platforms | Description |",
            "|------|---------|--------|-----------|-----------|-------------|",
        ]
    )
    for row in rows:
        header.append(
            "| "
            + " | ".join(
                _cell(field)
                for field in (
                    f"`{row.name}`",
                    row.display_name,
                    row.status,
                    row.lifecycle,
                    row.platforms,
                    row.description,
                )
            )
            + " |"
        )
    header.append("")
    return "\n".join(header)


def _cell(text: str) -> str:
    """Escape a markdown-table cell: collapse newlines and escape pipes."""
    return text.replace("\n", " ").replace("|", "\\|").strip() or "-"


def _summarise(description: str) -> str:
    """Take the first line / paragraph of the description and trim to fit a cell."""
    first = description.strip().split("\n", maxsplit=1)[0].strip()
    if len(first) <= _DESCRIPTION_MAX_CHARS:
        return first
    return first[: _DESCRIPTION_MAX_CHARS - 1].rstrip() + "..."
